#!/bin/bash

set -e
set -o pipefail
set -u

{
	hjson-cli -j
	
	{
		echo "{
			neigh:
			{
				$name:
				{
					id: $id
					signpub: $signpub
					exchpub: $exchpub
					noisepub: $noisepub
					
					addrs: {"
					for alias_address in $addrs
					do
						[[ $alias_address =~ (.+)=(.+) ]]
						alias=${BASH_REMATCH[1]}
						address=${BASH_REMATCH[2]}
						if ! [[ $address =~ ^\| ]] && ! [[ $address =~ : ]]; then address="$address:5400"; fi
						echo "$alias: $address"
					done
					echo "}
					
					calls:
					[
						{
							cron: \"* * * * *\"
							when-tx-exists: true
						}
					]
					
					incoming: \"/var/incoming/nncp/$name\"
				}
			}
		}"
	}|\
	hjson-cli -j
}|\
jq -s '.[0] * .[1]' |\
hjson-cli
