#!/usr/bin/env perl

for my $desktopfile (glob "/usr/share/applications/*.desktop")
{
	my ($basename) = $desktopfile =~ /([^\/]+)$/;
	open my $fh, '<', $desktopfile or die $!;
	my @categories = ();
	my ($appname) = $basename =~ /^(.+?)\.desktop$/;
	
	while(<$fh>)
	{
		chomp;
		if(/^Categories=(.+)$/)
		{
			@categories = split /;/, $1;
		}
		elsif(/^Name=(.+)$/)
		{
			$appname = $1;
		}
	}
	
	close $fh;
	
	for my $cat (@categories)
	{
		my $appname_safe = $appname; $appname_safe =~ s{/}{⁄}g;
		my $targetfile = "/opt/applications/$cat/$appname_safe.desktop";
		if(!-s $targetfile)
		{
			mkdir "/opt/applications/$cat";
			system "cp", "-f", $desktopfile, $targetfile;
		}
		chmod 0755, $targetfile;
	}
}
