#!/usr/bin/env perl

# search common XDG_DATA_DIRS for application description files.
# this list is in reverse-precedence order.
@appdirs = (
	"/var/lib/flatpak/exports/share/applications",
	"/usr/share/gnome/applications",
	"/usr/local/share/applications",
	"/usr/share/applications",
);

for my $appdir (@appdirs)
{
	for my $desktopfile (glob "$appdir/*.desktop")
	{
		my ($basename) = $desktopfile =~ /([^\/]+)$/;
		my @categories = ();
		my ($appname) = $basename =~ /^(.+?)\.desktop$/;
		
		open my $fh, '<', $desktopfile or die $!;
		while(<$fh>)
		{
			chomp;
			if(/^Categories=(.+)$/)
			{
				@categories = split /;/, $1;
			}
			elsif(/^Name=(.+)$/)
			{
				$appname = $1;
			}
		}
		close $fh;
		
		for my $cat (@categories)
		{
			# replace path separator to a look-alike unicode char
			my $appname_safe = $appname; $appname_safe =~ s{/}{⁄}g;
			my $targetfile = "/opt/applications/$cat/$appname_safe.desktop";
			mkdir "/opt/applications/$cat";
			system 'install', '--compare', '-m', '0755', $desktopfile, $targetfile;
		}
	}
}
