#!/bin/bash

setxkbmap us intl

xrdb -override ~/.Xresources 

# systray progs
{
	sleep 1
	xfce4-clipman &
	sudo nm-applet &
	blueman-applet &
	pasystray &
}

synclient VertTwoFingerScroll=1
synclient HorizTwoFingerScroll=1
synclient TapButton1=1
synclient TapButton2=3
synclient TapButton3=2

