#!/bin/bash

current_kbd=`setxkbmap -query`
layout=`echo "$current_kbd" | grep ^layout: | cut -f2 -d: | sed -e 's/ //g'`
variant=`echo "$current_kbd" | grep ^variant: | cut -f2 -d: | sed -e 's/ //g'`
current_code="$layout${variant:+ }$variant"

dIFS=$IFS
IFS=,
KeyboardLayouts=(`grep ^KeyboardLayouts= ~/.icewm/preferences | cut -f2 -d=`)
IFS=$dIFS

kbd_layouts=()

for code in "${KeyboardLayouts[@]}"
do
	code=${code//\"/}
	if [ "$code" != "$current_code" ]
	then
		kbd_layouts+=("$code")
	fi
done

for code in "$current_code" "${kbd_layouts[@]}"
do
	echo "prog \"$code\" keyboard setxkbmap $code"
done
