#!/bin/bash

privilege_command=${0##*/}
command_path=/usr/bin

if [ "$UID" = 0 -o \( $# != 0 -a ".$1" != ".$USER" \) ]
then
	exec "$command_path/$privilege_command" "$@"
fi
        
exec sudo /bin/sh -c "$command_path/$privilege_command \$SUDO_USER"
