#!/usr/bin/env perl

use Data::Dumper;

while(<STDIN>)
{
	chomp;
	if(/^\s*(?!#)(?<service>\S+)\s+(?<port>\d+)\/(?<proto>\S+)\s*(?<comments>.*)/)
	{
		my %s = %+;
		for my $f (keys %s)
		{
			my $len = length $s{$f};
			$maxlen{$f} = $len if $maxlen{$f} < $len;
		}
		push @Service, \%s;
	}
}

warn sprintf "%d records\n", scalar @Service;

$cmpkey_fmt = sprintf '%%0%ds %%-%ds %%-%ds %%-%ds', map {$maxlen{$_}} qw/port proto service comments/;
#warn Dumper $cmpkey_fmt;

for my $s (@Service)
{
	my $k = sprintf $cmpkey_fmt, map {$s->{$_}} qw/port proto service comments/;
	#warn $k;
	$s->{cmpkey} = $k;
}

# remove duplicate items
my %seen;
my @Service = grep { !$seen{ $_->{cmpkey} }++ } @Service;

for my $s (sort {$a->{cmpkey} cmp $b->{cmpkey}} @Service)
{
	printf "%s\t%s/%s\t%s\n", $s->{service}, $s->{port}, $s->{proto}, $s->{comments};
}
